// Generated by https://quicktype.io

class PostsModel {
  int userId;
  int id;
  String title;
  String body;

  PostsModel({
    required this.userId,
    required this.id,
    required this.title,
    required this.body,
  });
}
